const prefix: string = 'outlook';

export default {
  CALENDAR_ADD: `${prefix} calendar add`,
  CALENDAR_GET: `${prefix} calendar get`,
  CALENDAR_LIST: `${prefix} calendar list`,
  CALENDAR_REMOVE: `${prefix} calendar remove`,
  CALENDAR_SET: `${prefix} calendar set`,
  CALENDARGROUP_GET: `${prefix} calendargroup get`,
  CALENDARGROUP_LIST: `${prefix} calendargroup list`,
  CALENDARGROUP_REMOVE: `${prefix} calendargroup remove`,
  CALENDARGROUP_SET: `${prefix} calendargroup set`,
  EVENT_CANCEL: `${prefix} event cancel`,
  EVENT_GET: `${prefix} event get`,
  EVENT_LIST: `${prefix} event list`,
  EVENT_REMOVE: `${prefix} event remove`,
  MAIL_SEARCHFOLDER_ADD: `${prefix} mail searchfolder add`,
  MAIL_SEND: `${prefix} mail send`,
  MAILBOX_SETTINGS_GET: `${prefix} mailbox settings get`,
  MAILBOX_SETTINGS_SET: `${prefix} mailbox settings set`,
  MESSAGE_GET: `${prefix} message get`,
  MESSAGE_LIST: `${prefix} message list`,
  MESSAGE_MOVE: `${prefix} message move`,
  MESSAGE_REMOVE: `${prefix} message remove`,
  REPORT_MAILACTIVITYCOUNTS: `${prefix} report mailactivitycounts`,
  REPORT_MAILACTIVITYUSERCOUNTS: `${prefix} report mailactivityusercounts`,
  REPORT_MAILACTIVITYUSERDETAIL: `${prefix} report mailactivityuserdetail`,
  REPORT_MAILAPPUSAGEAPPSUSERCOUNTS: `${prefix} report mailappusageappsusercounts`,
  REPORT_MAILAPPUSAGEUSERCOUNTS: `${prefix} report mailappusageusercounts`,
  REPORT_MAILAPPUSAGEUSERDETAIL: `${prefix} report mailappusageuserdetail`,
  REPORT_MAILAPPUSAGEVERSIONSUSERCOUNTS: `${prefix} report mailappusageversionsusercounts`,
  REPORT_MAILBOXUSAGEDETAIL: `${prefix} report mailboxusagedetail`,
  REPORT_MAILBOXUSAGEMAILBOXCOUNT: `${prefix} report mailboxusagemailboxcount`,
  REPORT_MAILBOXUSAGEQUOTASTATUSMAILBOXCOUNTS: `${prefix} report mailboxusagequotastatusmailboxcounts`,
  REPORT_MAILBOXUSAGESTORAGE: `${prefix} report mailboxusagestorage`,
  ROOM_LIST: `${prefix} room list`,
  ROOMLIST_LIST: `${prefix} roomlist list`
};