const prefix: string = 'entra';

export default {
  ADMINISTRATIVEUNIT_ADD: `${prefix} administrativeunit add`,
  ADMINISTRATIVEUNIT_GET: `${prefix} administrativeunit get`,
  ADMINISTRATIVEUNIT_LIST: `${prefix} administrativeunit list`,
  ADMINISTRATIVEUNIT_REMOVE: `${prefix} administrativeunit remove`,
  ADMINISTRATIVEUNIT_MEMBER_ADD: `${prefix} administrativeunit member add`,
  ADMINISTRATIVEUNIT_MEMBER_GET: `${prefix} administrativeunit member get`,
  ADMINISTRATIVEUNIT_MEMBER_LIST: `${prefix} administrativeunit member list`,
  ADMINISTRATIVEUNIT_MEMBER_REMOVE: `${prefix} administrativeunit member remove`,
  ADMINISTRATIVEUNIT_ROLEASSIGNMENT_ADD: `${prefix} administrativeunit roleassignment add`,
  APP_ADD: `${prefix} app add`,
  APP_GET: `${prefix} app get`,
  APP_LIST: `${prefix} app list`,
  APP_REMOVE: `${prefix} app remove`,
  APP_SET: `${prefix} app set`,
  APP_PERMISSION_ADD: `${prefix} app permission add`,
  APP_PERMISSION_LIST: `${prefix} app permission list`,
  APP_ROLE_ADD: `${prefix} app role add`,
  APP_ROLE_LIST: `${prefix} app role list`,
  APP_ROLE_REMOVE: `${prefix} app role remove`,
  APPREGISTRATION_ADD: `${prefix} appregistration add`,
  APPREGISTRATION_GET: `${prefix} appregistration get`,
  APPREGISTRATION_LIST: `${prefix} appregistration list`,
  APPREGISTRATION_REMOVE: `${prefix} appregistration remove`,
  APPREGISTRATION_SET: `${prefix} appregistration set`,
  APPREGISTRATION_PERMISSION_ADD: `${prefix} appregistration permission add`,
  APPREGISTRATION_ROLE_ADD: `${prefix} appregistration role add`,
  APPREGISTRATION_ROLE_LIST: `${prefix} appregistration role list`,
  APPREGISTRATION_ROLE_REMOVE: `${prefix} appregistration role remove`,
  APPROLEASSIGNMENT_ADD: `${prefix} approleassignment add`,
  APPROLEASSIGNMENT_LIST: `${prefix} approleassignment list`,
  APPROLEASSIGNMENT_REMOVE: `${prefix} approleassignment remove`,
  ENTERPRISEAPP_ADD: `${prefix} enterpriseapp add`,
  ENTERPRISEAPP_GET: `${prefix} enterpriseapp get`,
  ENTERPRISEAPP_LIST: `${prefix} enterpriseapp list`,
  GROUP_ADD: `${prefix} group add`,
  GROUP_GET: `${prefix} group get`,
  GROUP_LIST: `${prefix} group list`,
  GROUP_REMOVE: `${prefix} group remove`,
  GROUP_USER_ADD: `${prefix} group user add`,
  GROUP_USER_LIST: `${prefix} group user list`,
  GROUPSETTING_ADD: `${prefix} groupsetting add`,
  GROUPSETTING_GET: `${prefix} groupsetting get`,
  GROUPSETTING_LIST: `${prefix} groupsetting list`,
  GROUPSETTING_REMOVE: `${prefix} groupsetting remove`,
  GROUPSETTING_SET: `${prefix} groupsetting set`,
  GROUPSETTINGTEMPLATE_GET: `${prefix} groupsettingtemplate get`,
  GROUPSETTINGTEMPLATE_LIST: `${prefix} groupsettingtemplate list`,
  LICENSE_LIST: `${prefix} license list`,
  M365GROUP_ADD: `${prefix} m365group add`,
  M365GROUP_GET: `${prefix} m365group get`,
  M365GROUP_LIST: `${prefix} m365group list`,
  M365GROUP_CONVERSATION_LIST: `${prefix} m365group conversation list`,
  M365GROUP_CONVERSATION_POST_LIST: `${prefix} m365group conversation post list`,
  M365GROUP_RECYCLEBINITEM_CLEAR: `${prefix} m365group recyclebinitem clear`,
  M365GROUP_RECYCLEBINITEM_LIST: `${prefix} m365group recyclebinitem list`,
  M365GROUP_RECYCLEBINITEM_REMOVE: `${prefix} m365group recyclebinitem remove`,
  M365GROUP_RECYCLEBINITEM_RESTORE: `${prefix} m365group recyclebinitem restore`,
  M365GROUP_SET: `${prefix} m365group set`,
  M365GROUP_TEAMIFY: `${prefix} m365group teamify`,
  M365GROUP_REMOVE: `${prefix} m365group remove`,
  M365GROUP_RENEW: `${prefix} m365group renew`,
  M365GROUP_REPORT_ACTIVITYCOUNTS: `${prefix} m365group report activitycounts`,
  M365GROUP_REPORT_ACTIVITYDETAIL: `${prefix} m365group report activitydetail`,
  M365GROUP_REPORT_ACTIVITYFILECOUNTS: `${prefix} m365group report activityfilecounts`,
  M365GROUP_REPORT_ACTIVITYGROUPCOUNTS: `${prefix} m365group report activitygroupcounts`,
  M365GROUP_REPORT_ACTIVITYSTORAGE: `${prefix} m365group report activitystorage`,
  M365GROUP_USER_ADD: `${prefix} m365group user add`,
  M365GROUP_USER_LIST: `${prefix} m365group user list`,
  M365GROUP_USER_REMOVE: `${prefix} m365group user remove`,
  M365GROUP_USER_SET: `${prefix} m365group user set`,
  OAUTH2GRANT_ADD: `${prefix} oauth2grant add`,
  OAUTH2GRANT_LIST: `${prefix} oauth2grant list`,
  OAUTH2GRANT_REMOVE: `${prefix} oauth2grant remove`,
  OAUTH2GRANT_SET: `${prefix} oauth2grant set`,
  PIM_ROLE_ASSIGNMENT_LIST: `${prefix} pim role assignment list`,
  POLICY_LIST: `${prefix} policy list`,
  SITECLASSIFICATION_DISABLE: `${prefix} siteclassification disable`,
  SITECLASSIFICATION_ENABLE: `${prefix} siteclassification enable`,
  SITECLASSIFICATION_GET: `${prefix} siteclassification get`,
  SITECLASSIFICATION_SET: `${prefix} siteclassification set`,
  SP_ADD: `${prefix} sp add`,
  SP_GET: `${prefix} sp get`,
  SP_LIST: `${prefix} sp list`,
  USER_ADD: `${prefix} user add`,
  USER_GET: `${prefix} user get`,
  USER_GUEST_ADD: `${prefix} user guest add`,
  USER_HIBP: `${prefix} user hibp`,
  USER_LICENSE_ADD: `${prefix} user license add`,
  USER_LICENSE_LIST: `${prefix} user license list`,
  USER_LICENSE_REMOVE: `${prefix} user license remove`,
  USER_LIST: `${prefix} user list`,
  USER_PASSWORD_VALIDATE: `${prefix} user password validate`,
  USER_RECYCLEBINITEM_CLEAR: `${prefix} user recyclebinitem clear`,
  USER_RECYCLEBINITEM_LIST: `${prefix} user recyclebinitem list`,
  USER_RECYCLEBINITEM_REMOVE: `${prefix} user recyclebinitem remove`,
  USER_REGISTRATIONDETAILS_LIST: `${prefix} user registrationdetails list`,
  USER_REMOVE: `${prefix} user remove`,
  USER_RECYCLEBINITEM_RESTORE: `${prefix} user recyclebinitem restore`,
  USER_SET: `${prefix} user set`,
  USER_SIGNIN_LIST: `${prefix} user signin list`
};
