const prefix: string = 'planner';

export default {
  BUCKET_ADD: `${prefix} bucket add`,
  BUCKET_GET: `${prefix} bucket get`,
  BUCKET_LIST: `${prefix} bucket list`,
  BUCKET_SET: `${prefix} bucket set`,
  BUCKET_REMOVE: `${prefix} bucket remove`,
  PLAN_ADD: `${prefix} plan add`,
  PLAN_GET: `${prefix} plan get`,
  PLAN_LIST: `${prefix} plan list`,
  PLAN_REMOVE: `${prefix} plan remove`,
  PLAN_SET: `${prefix} plan set`,
  ROSTER_ADD: `${prefix} roster add`,
  ROSTER_GET: `${prefix} roster get`,
  ROSTER_MEMBER_ADD: `${prefix} roster member add`,
  ROSTER_MEMBER_LIST: `${prefix} roster member list`,
  ROSTER_REMOVE: `${prefix} roster remove`,
  TASK_ADD: `${prefix} task add`,
  TASK_CHECKLISTITEM_ADD: `${prefix} task checklistitem add`,
  TASK_CHECKLISTITEM_LIST: `${prefix} task checklistitem list`,
  TASK_CHECKLISTITEM_REMOVE: `${prefix} task checklistitem remove`,
  TASK_GET: `${prefix} task get`,
  TASK_LIST: `${prefix} task list`,
  TASK_REFERENCE_ADD: `${prefix} task reference add`,
  TASK_REFERENCE_LIST: `${prefix} task reference list`,
  TASK_REFERENCE_REMOVE: `${prefix} task reference remove`,
  TASK_REMOVE: `${prefix} task remove`,
  TASK_SET: `${prefix} task set`,
  TENANT_SETTINGS_LIST: `${prefix} tenant settings list`,
  TENANT_SETTINGS_SET: `${prefix} tenant settings set`
};
