const prefix: string = 'teams';

export default {
  TEAMS_APP_INSTALL: `${prefix} app install`,
  TEAMS_APP_LIST: `${prefix} app list`,
  TEAMS_APP_PUBLISH: `${prefix} app publish`,
  TEAMS_APP_REMOVE: `${prefix} app remove`,
  TEAMS_APP_UNINSTALL: `${prefix} app uninstall`,
  TEAMS_APP_UPDATE: `${prefix} app update`,
  TEAMS_CHANNEL_ADD: `${prefix} channel add`,
  TEAMS_CHANNEL_GET: `${prefix} channel get`,
  TEAMS_CHANNEL_LIST: `${prefix} channel list`,
  TEAMS_CHANNEL_REMOVE: `${prefix} channel remove`,
  TEAMS_CHANNEL_SET: `${prefix} channel set`,
  TEAMS_FUNSETTINGS_LIST: `${prefix} funsettings list`,
  TEAMS_FUNSETTINGS_SET: `${prefix} funsettings set`,
  TEAMS_GUESTSETTINGS_LIST: `${prefix} guestsettings list`,
  TEAMS_GUESTSETTINGS_SET: `${prefix} guestsettings set`,
  TEAMS_MEMBERSETTINGS_LIST: `${prefix} membersettings list`,
  TEAMS_MEMBERSETTINGS_SET: `${prefix} membersettings set`,
  TEAMS_MESSAGE_GET: `${prefix} message get`,
  TEAMS_MESSAGE_LIST: `${prefix} message list`,
  TEAMS_MESSAGE_REPLY_LIST: `${prefix} message reply list`,
  TEAMS_MESSAGINGSETTINGS_LIST: `${prefix} messagingsettings list`,
  TEAMS_MESSAGINGSETTINGS_SET: `${prefix} messagingsettings set`,
  TEAMS_REPORT_DEVICEUSAGEDISTRIBUTIONUSERCOUNTS: `${prefix} report deviceusagedistributionusercounts`,
  TEAMS_REPORT_DEVICEUSAGEUSERCOUNTS: `${prefix} report deviceusageusercounts`,
  TEAMS_REPORT_DEVICEUSAGEUSERDETAIL: `${prefix} report deviceusageuserdetail`,
  TEAMS_REPORT_USERACTIVITYCOUNTS: `${prefix} report useractivitycounts`,
  TEAMS_REPORT_USERACTIVITYUSERCOUNTS: `${prefix} report useractivityusercounts`,
  TEAMS_REPORT_USERACTIVITYUSERDETAIL: `${prefix} report useractivityuserdetail`,
  TEAMS_TAB_ADD: `${prefix} tab add`,
  TEAMS_TAB_LIST: `${prefix} tab list`,
  TEAMS_TAB_REMOVE: `${prefix} tab remove`,
  TEAMS_TEAM_ADD: `${prefix} team add`,
  TEAMS_TEAM_ARCHIVE: `${prefix} team archive`,
  TEAMS_TEAM_CLONE: `${prefix} team clone`,
  TEAMS_TEAM_LIST: `${prefix} team list`,
  TEAMS_TEAM_REMOVE: `${prefix} team remove`,
  TEAMS_TEAM_SET: `${prefix} team set`,
  TEAMS_TEAM_UNARCHIVE: `${prefix} team unarchive`,
  TEAMS_USER_ADD: `${prefix} user add`,
  TEAMS_USER_LIST: `${prefix} user list`,
  TEAMS_USER_REMOVE: `${prefix} user remove`,
  TEAMS_USER_SET: `${prefix} user set`,
  TEAMS_USER_APP_ADD: `${prefix} user app add`
};