const prefix: string = 'teams';

export default {
  APP_INSTALL: `${prefix} app install`,
  APP_LIST: `${prefix} app list`,
  APP_PUBLISH: `${prefix} app publish`,
  APP_REMOVE: `${prefix} app remove`,
  APP_UNINSTALL: `${prefix} app uninstall`,
  APP_UPDATE: `${prefix} app update`,
  CHANNEL_ADD: `${prefix} channel add`,
  CHANNEL_GET: `${prefix} channel get`,
  CHANNEL_LIST: `${prefix} channel list`,
  CHANNEL_MEMBER_LIST: `${prefix} channel member list`,
  CHANNEL_MEMBER_SET: `${prefix} channel member set`,
  CHANNEL_REMOVE: `${prefix} channel remove`,
  CHANNEL_SET: `${prefix} channel set`,
  CHAT_GET: `${prefix} chat get`,
  CHAT_LIST: `${prefix} chat list`,
  CHAT_MEMBER_LIST: `${prefix} chat member list`,
  CHAT_MESSAGE_LIST: `${prefix} chat message list`,
  CHAT_MESSAGE_SEND: `${prefix} chat message send`,
  CONVERSATIONMEMBER_ADD: `${prefix} conversationmember add`,
  CONVERSATIONMEMBER_LIST: `${prefix} conversationmember list`,
  FUNSETTINGS_LIST: `${prefix} funsettings list`,
  FUNSETTINGS_SET: `${prefix} funsettings set`,
  GUESTSETTINGS_LIST: `${prefix} guestsettings list`,
  GUESTSETTINGS_SET: `${prefix} guestsettings set`,
  MEMBERSETTINGS_LIST: `${prefix} membersettings list`,
  MEMBERSETTINGS_SET: `${prefix} membersettings set`,
  MESSAGE_GET: `${prefix} message get`,
  MESSAGE_LIST: `${prefix} message list`,
  MESSAGE_REPLY_LIST: `${prefix} message reply list`,
  MESSAGINGSETTINGS_LIST: `${prefix} messagingsettings list`,
  MESSAGINGSETTINGS_SET: `${prefix} messagingsettings set`,
  REPORT_DEVICEUSAGEDISTRIBUTIONUSERCOUNTS: `${prefix} report deviceusagedistributionusercounts`,
  REPORT_DEVICEUSAGEUSERCOUNTS: `${prefix} report deviceusageusercounts`,
  REPORT_DEVICEUSAGEUSERDETAIL: `${prefix} report deviceusageuserdetail`,
  REPORT_DIRECTROUTINGCALLS: `${prefix} report directroutingcalls`,
  REPORT_PSTNCALLS: `${prefix} report pstncalls`,
  REPORT_USERACTIVITYCOUNTS: `${prefix} report useractivitycounts`,
  REPORT_USERACTIVITYUSERCOUNTS: `${prefix} report useractivityusercounts`,
  REPORT_USERACTIVITYUSERDETAIL: `${prefix} report useractivityuserdetail`,
  TAB_ADD: `${prefix} tab add`,
  TAB_GET: `${prefix} tab get`,
  TAB_LIST: `${prefix} tab list`,
  TAB_REMOVE: `${prefix} tab remove`,
  TEAM_ADD: `${prefix} team add`,
  TEAM_ARCHIVE: `${prefix} team archive`,
  TEAM_CLONE: `${prefix} team clone`,
  TEAM_GET: `${prefix} team get`,
  TEAM_LIST: `${prefix} team list`,
  TEAM_REMOVE: `${prefix} team remove`,
  TEAM_SET: `${prefix} team set`,
  TEAM_UNARCHIVE: `${prefix} team unarchive`,
  USER_ADD: `${prefix} user add`,
  USER_LIST: `${prefix} user list`,
  USER_REMOVE: `${prefix} user remove`,
  USER_SET: `${prefix} user set`,
  USER_APP_ADD: `${prefix} user app add`,
  USER_APP_LIST: `${prefix} user app list`,
  USER_APP_REMOVE: `${prefix} user app remove`
};
