const prefix: string = 'aad';

export default {
  APPROLEASSIGNMENT_ADD: `${prefix} approleassignment add`,
  APPROLEASSIGNMENT_LIST: `${prefix} approleassignment list`,
  GROUPSETTING_ADD: `${prefix} groupsetting add`,
  GROUPSETTING_GET: `${prefix} groupsetting get`,
  GROUPSETTING_LIST: `${prefix} groupsetting list`,
  GROUPSETTING_REMOVE: `${prefix} groupsetting remove`,
  GROUPSETTING_SET: `${prefix} groupsetting set`,
  GROUPSETTINGTEMPLATE_GET: `${prefix} groupsettingtemplate get`,
  GROUPSETTINGTEMPLATE_LIST: `${prefix} groupsettingtemplate list`,
  O365GROUP_ADD: `${prefix} o365group add`,
  O365GROUP_GET: `${prefix} o365group get`,
  O365GROUP_LIST: `${prefix} o365group list`,
  O365GROUP_SET: `${prefix} o365group set`,
  O365GROUP_TEAMIFY: `${prefix} o365group teamify`,
  O365GROUP_REMOVE: `${prefix} o365group remove`,
  O365GROUP_RENEW: `${prefix} o365group renew`,
  O365GROUP_REPORT_ACTIVITYCOUNTS: `${prefix} o365group report activitycounts`,
  O365GROUP_REPORT_ACTIVITYDETAIL: `${prefix} o365group report activitydetail`,
  O365GROUP_REPORT_ACTIVITYFILECOUNTS: `${prefix} o365group report activityfilecounts`,
  O365GROUP_REPORT_ACTIVITYGROUPCOUNTS: `${prefix} o365group report activitygroupcounts`,
  O365GROUP_REPORT_ACTIVITYSTORAGE: `${prefix} o365group report activitystorage`,
  O365GROUP_RESTORE: `${prefix} o365group restore`,
  O365GROUP_USER_ADD: `${prefix} o365group user add`,
  O365GROUP_USER_LIST: `${prefix} o365group user list`,
  O365GROUP_USER_REMOVE: `${prefix} o365group user remove`,
  O365GROUP_USER_SET: `${prefix} o365group user set`,
  OAUTH2GRANT_ADD: `${prefix} oauth2grant add`,
  OAUTH2GRANT_LIST: `${prefix} oauth2grant list`,
  OAUTH2GRANT_REMOVE: `${prefix} oauth2grant remove`,
  OAUTH2GRANT_SET: `${prefix} oauth2grant set`,
  SITECLASSIFICATION_DISABLE: `${prefix} siteclassification disable`,
  SITECLASSIFICATION_ENABLE: `${prefix} siteclassification enable`,
  SITECLASSIFICATION_GET: `${prefix} siteclassification get`,
  SITECLASSIFICATION_SET: `${prefix} siteclassification set`,
  SP_GET: `${prefix} sp get`,
  USER_GET: `${prefix} user get`,
  USER_LIST: `${prefix} user list`
};