const prefix: string = 'graph';

export default {
  GROUPSETTING_ADD: `${prefix} groupsetting add`,
  GROUPSETTING_GET: `${prefix} groupsetting get`,
  GROUPSETTING_LIST: `${prefix} groupsetting list`,
  GROUPSETTING_REMOVE: `${prefix} groupsetting remove`,
  GROUPSETTING_SET: `${prefix} groupsetting set`,
  GROUPSETTINGTEMPLATE_GET: `${prefix} groupsettingtemplate get`,
  GROUPSETTINGTEMPLATE_LIST: `${prefix} groupsettingtemplate list`,
  O365GROUP_ADD: `${prefix} o365group add`,
  O365GROUP_GET: `${prefix} o365group get`,
  O365GROUP_LIST: `${prefix} o365group list`,
  O365GROUP_SET: `${prefix} o365group set`,
  O365GROUP_REMOVE: `${prefix} o365group remove`,
  O365GROUP_RENEW: `${prefix} o365group renew`,
  O365GROUP_RESTORE: `${prefix} o365group restore`,
  O365GROUP_USER_ADD: `${prefix} o365group user add`,
  O365GROUP_USER_LIST: `${prefix} o365group user list`,
  O365GROUP_USER_REMOVE: `${prefix} o365group user remove`,
  O365GROUP_USER_SET: `${prefix} o365group user set`,
  PLANNER_TASK_LIST: `${prefix} planner task list`,
  REPORT_TEAMSDEVICEUSAGEUSERDETAIL: `${prefix} report teamsdeviceusageuserdetail`,
  SCHEMAEXTENSION_ADD: `${prefix} schemaextension add`,
  SITECLASSIFICATION_DISABLE: `${prefix} siteclassification disable`,
  SITECLASSIFICATION_ENABLE: `${prefix} siteclassification enable`,
  SITECLASSIFICATION_GET: `${prefix} siteclassification get`,
  SITECLASSIFICATION_SET: `${prefix} siteclassification set`,
  TEAMS_ADD: `${prefix} teams add`,
  TEAMS_APP_INSTALL: `${prefix} teams app install`,
  TEAMS_APP_LIST: `${prefix} teams app list`,
  TEAMS_APP_PUBLISH: `${prefix} teams app publish`,
  TEAMS_APP_REMOVE: `${prefix} teams app remove`,
  TEAMS_APP_UNINSTALL: `${prefix} teams app uninstall`,
  TEAMS_APP_UPDATE: `${prefix} teams app update`,
  TEAMS_ARCHIVE: `${prefix} teams archive`,
  TEAMS_GUESTSETTINGS_SET: `${prefix} teams guestsettings set`,
  TEAMS_LIST: `${prefix} teams list`,
  TEAMS_CHANNEL_ADD: `${prefix} teams channel add`,
  TEAMS_CHANNEL_GET: `${prefix} teams channel get`,
  TEAMS_CHANNEL_LIST: `${prefix} teams channel list`,
  TEAMS_CHANNEL_MESSAGE_GET: `${prefix} teams channel message get`,
  TEAMS_CHANNEL_SET: `${prefix} teams channel set`,
  TEAMS_CLONE: `${prefix} teams clone`,
  TEAMS_FUNSETTINGS_LIST: `${prefix} teams funsettings list`,
  TEAMS_FUNSETTINGS_SET: `${prefix} teams funsettings set`,
  TEAMS_GUESTSETTINGS_LIST: `${prefix} teams guestsettings list`,
  TEAMS_MEMBERSETTINGS_LIST: `${prefix} teams membersettings list`,
  TEAMS_MEMBERSETTINGS_SET: `${prefix} teams membersettings set`,
  TEAMS_MESSAGE_GET: `${prefix} teams message get`,
  TEAMS_MESSAGE_LIST: `${prefix} teams message list`,
  TEAMS_MESSAGINGSETTINGS_LIST: `${prefix} teams messagingsettings list`,
  TEAMS_MESSAGINGSETTINGS_SET: `${prefix} teams messagingsettings set`,
  TEAMS_REMOVE: `${prefix} teams remove`,
  TEAMS_SET: `${prefix} teams set`,
  TEAMS_TAB_LIST: `${prefix} teams tab list`,
  TEAMS_UNARCHIVE: `${prefix} teams unarchive`,
  TEAMS_USER_ADD: `${prefix} teams user add`,
  TEAMS_USER_LIST: `${prefix} teams user list`,
  TEAMS_USER_REMOVE: `${prefix} teams user remove`,
  TEAMS_USER_SET: `${prefix} teams user set`,
  USER_GET: `${prefix} user get`,
  USER_LIST: `${prefix} user list`,
  USER_SENDMAIL: `${prefix} user sendmail`
};