const prefix: string = 'graph';

export default {
  CONNECT: `${prefix} connect`,
  DISCONNECT: `${prefix} disconnect`,
  GROUPSETTING_ADD: `${prefix} groupsetting add`,
  GROUPSETTING_GET: `${prefix} groupsetting get`,
  GROUPSETTING_LIST: `${prefix} groupsetting list`,
  GROUPSETTING_REMOVE: `${prefix} groupsetting remove`,
  GROUPSETTING_SET: `${prefix} groupsetting set`,
  GROUPSETTINGTEMPLATE_GET: `${prefix} groupsettingtemplate get`,
  GROUPSETTINGTEMPLATE_LIST: `${prefix} groupsettingtemplate list`,
  LOGIN: `${prefix} login`,
  LOGOUT: `${prefix} logout`,
  O365GROUP_ADD: `${prefix} o365group add`,
  O365GROUP_GET: `${prefix} o365group get`,
  O365GROUP_LIST: `${prefix} o365group list`,
  O365GROUP_SET: `${prefix} o365group set`,
  O365GROUP_REMOVE: `${prefix} o365group remove`,
  O365GROUP_RESTORE: `${prefix} o365group restore`,
  SITECLASSIFICATION_DISABLE: `${prefix} siteclassification disable`,
  SITECLASSIFICATION_ENABLE: `${prefix} siteclassification enable`,
  SITECLASSIFICATION_GET: `${prefix} siteclassification get`,
  SITECLASSIFICATION_SET: `${prefix} siteclassification set`,
  STATUS: `${prefix} status`,
  TEAMS_LIST: `${prefix} teams list`,
  TEAMS_CHANNEL_ADD: `${prefix} teams channel add`,
  TEAMS_CHANNEL_MESSAGE_GET: `${prefix} teams channel message get`,
  TEAMS_MESSAGE_GET: `${prefix} teams message get`,
  TEAMS_MESSAGE_LIST: `${prefix} teams message list`,
  USER_GET: `${prefix} user get`,
  USER_LIST: `${prefix} user list`,
  USER_SENDMAIL: `${prefix} user sendmail`,
};