const prefix: string = 'viva';

export default {
  CONNECTIONS_APP_CREATE: `${prefix} connections app create`,
  ENGAGE_COMMUNITY_ADD: `${prefix} engage community add`,
  ENGAGE_COMMUNITY_GET: `${prefix} engage community get`,
  ENGAGE_COMMUNITY_LIST: `${prefix} engage community list`,
  ENGAGE_COMMUNITY_REMOVE: `${prefix} engage community remove`,
  ENGAGE_COMMUNITY_SET: `${prefix} engage community set`,
  ENGAGE_COMMUNITY_USER_ADD: `${prefix} engage community user add`,
  ENGAGE_COMMUNITY_USER_LIST: `${prefix} engage community user list`,
  ENGAGE_COMMUNITY_USER_REMOVE: `${prefix} engage community user remove`,
  ENGAGE_MESSAGE_ADD: `${prefix} engage message add`,
  ENGAGE_MESSAGE_GET: `${prefix} engage message get`,
  ENGAGE_MESSAGE_LIKE_SET: `${prefix} engage message like set`,
  ENGAGE_MESSAGE_LIST: `${prefix} engage message list`,
  ENGAGE_MESSAGE_REMOVE: `${prefix} engage message remove`,
  ENGAGE_NETWORK_LIST: `${prefix} engage network list`,
  ENGAGE_REPORT_ACTIVITYCOUNTS: `${prefix} engage report activitycounts`,
  ENGAGE_REPORT_ACTIVITYUSERCOUNTS: `${prefix} engage report activityusercounts`,
  ENGAGE_REPORT_ACTIVITYUSERDETAIL: `${prefix} engage report activityuserdetail`,
  ENGAGE_REPORT_DEVICEUSAGEDISTRIBUTIONUSERCOUNTS: `${prefix} engage report deviceusagedistributionusercounts`,
  ENGAGE_REPORT_DEVICEUSAGEUSERCOUNTS: `${prefix} engage report deviceusageusercounts`,
  ENGAGE_REPORT_DEVICEUSAGEUSERDETAIL: `${prefix} engage report deviceusageuserdetail`,
  ENGAGE_REPORT_GROUPSACTIVITYCOUNTS: `${prefix} engage report groupsactivitycounts`,
  ENGAGE_REPORT_GROUPSACTIVITYDETAIL: `${prefix} engage report groupsactivitydetail`,
  ENGAGE_REPORT_GROUPSACTIVITYGROUPCOUNTS: `${prefix} engage report groupsactivitygroupcounts`,
  ENGAGE_ROLE_LIST: `${prefix} engage role list`,
  ENGAGE_ROLE_MEMBER_LIST: `${prefix} engage role member list`,
  ENGAGE_ROLE_MEMBER_REMOVE: `${prefix} engage role member remove`,
  ENGAGE_SEARCH: `${prefix} engage search`,
  ENGAGE_USER_GET: `${prefix} engage user get`,
  ENGAGE_USER_LIST: `${prefix} engage user list`
};