const prefix: string = 'spo';

export default {
  APP_ADD: `${prefix} app add`,
  APP_DEPLOY: `${prefix} app deploy`,
  APP_GET: `${prefix} app get`,
  APP_INSTALL: `${prefix} app install`,
  APP_LIST: `${prefix} app list`,
  APP_REMOVE: `${prefix} app remove`,
  APP_RETRACT: `${prefix} app retract`,
  APP_UNINSTALL: `${prefix} app uninstall`,
  APP_UPGRADE: `${prefix} app upgrade`,
  CDN_GET: `${prefix} cdn get`,
  CDN_ORIGIN_ADD: `${prefix} cdn origin add`,
  CDN_ORIGIN_LIST: `${prefix} cdn origin list`,
  CDN_ORIGIN_REMOVE: `${prefix} cdn origin remove`,
  CDN_POLICY_LIST: `${prefix} cdn policy list`,
  CDN_POLICY_SET: `${prefix} cdn policy set`,
  CDN_SET: `${prefix} cdn set`,
  CONNECT: `${prefix} connect`,
  CUSTOMACTION_ADD: `${prefix} customaction add`,
  CUSTOMACTION_GET: `${prefix} customaction get`,
  CUSTOMACTION_LIST: `${prefix} customaction list`,
  CUSTOMACTION_REMOVE: `${prefix} customaction remove`,
  DISCONNECT: `${prefix} disconnect`,
  EXTERNALUSER_LIST: `${prefix} externaluser list`,
  LIST_GET: `${prefix} list get`,
  SERVICEPRINCIPAL_GRANT_LIST: `${prefix} serviceprincipal grant list`,
  SERVICEPRINCIPAL_GRANT_REVOKE: `${prefix} serviceprincipal grant revoke`,
  SERVICEPRINCIPAL_PERMISSIONREQUEST_APPROVE: `${prefix} serviceprincipal permissionrequest approve`,
  SERVICEPRINCIPAL_PERMISSIONREQUEST_DENY: `${prefix} serviceprincipal permissionrequest deny`,
  SERVICEPRINCIPAL_PERMISSIONREQUEST_LIST: `${prefix} serviceprincipal permissionrequest list`,
  SERVICEPRINCIPAL_SET: `${prefix} serviceprincipal set`,
  SITE_ADD: `${prefix} site add`,
  SITE_APPCATALOG_ADD: `${prefix} site appcatalog add`,
  SITE_APPCATALOG_REMOVE: `${prefix} site appcatalog remove`,
  SITE_GET: `${prefix} site get`,
  SITE_LIST: `${prefix} site list`,
  SITEDESIGN_ADD: `${prefix} sitedesign add`,
  SITEDESIGN_GET: `${prefix} sitedesign get`,
  SITEDESIGN_LIST: `${prefix} sitedesign list`,
  SITEDESIGN_REMOVE: `${prefix} sitedesign remove`,
  SITEDESIGN_RIGHTS_GRANT: `${prefix} sitedesign rights grant`,
  SITEDESIGN_RIGHTS_REVOKE: `${prefix} sitedesign rights revoke`,
  SITESCRIPT_ADD: `${prefix} sitescript add`,
  SITESCRIPT_GET: `${prefix} sitescript get`,
  SITESCRIPT_LIST: `${prefix} sitescript list`,
  SITESCRIPT_REMOVE: `${prefix} sitescript remove`,
  SITESCRIPT_SET: `${prefix} sitescript set`,
  SP_GRANT_LIST: `${prefix} sp grant list`,
  SP_GRANT_REVOKE: `${prefix} sp grant revoke`,
  SP_PERMISSIONREQUEST_APPROVE: `${prefix} sp permissionrequest approve`,
  SP_PERMISSIONREQUEST_DENY: `${prefix} sp permissionrequest deny`,
  SP_PERMISSIONREQUEST_LIST: `${prefix} sp permissionrequest list`,
  SP_SET: `${prefix} sp set`,
  STATUS: `${prefix} status`,
  STORAGEENTITY_LIST: `${prefix} storageentity list`,
  STORAGEENTITY_GET: `${prefix} storageentity get`,
  STORAGEENTITY_SET: `${prefix} storageentity set`,
  STORAGEENTITY_REMOVE: `${prefix} storageentity remove`
};