const prefix: string = 'spo';

export default {
  APP_ADD: `${prefix} app add`,
  APP_DEPLOY: `${prefix} app deploy`,
  APP_GET: `${prefix} app get`,
  APP_INSTALL: `${prefix} app install`,
  APP_LIST: `${prefix} app list`,
  APP_REMOVE: `${prefix} app remove`,
  APP_RETRACT: `${prefix} app retract`,
  APP_UNINSTALL: `${prefix} app uninstall`,
  APP_UPGRADE: `${prefix} app upgrade`,
  CONNECT: `${prefix} connect`,
  DISCONNECT: `${prefix} disconnect`,
  STATUS: `${prefix} status`,
  STORAGEENTITY_LIST: `${prefix} storageentity list`,
  STORAGEENTITY_GET: `${prefix} storageentity get`,
  STORAGEENTITY_SET: `${prefix} storageentity set`,
  STORAGEENTITY_REMOVE: `${prefix} storageentity remove`,
  CDN_GET: `${prefix} cdn get`,
  CDN_SET: `${prefix} cdn set`,
  CDN_ORIGIN_LIST: `${prefix} cdn origin list`,
  CDN_ORIGIN_SET: `${prefix} cdn origin set`,
  CDN_ORIGIN_REMOVE: `${prefix} cdn origin remove`,
  CDN_POLICY_LIST: `${prefix} cdn policy list`,
  CDN_POLICY_SET: `${prefix} cdn policy set`,
  CUSTOMACTION_GET: `${prefix} customaction get`,
  CUSTOMACTION_LIST: `${prefix} customaction list`,
  SERVICEPRINCIPAL_PERMISSIONREQUEST_APPROVE: `${prefix} serviceprincipal permissionrequest approve`,
  SERVICEPRINCIPAL_PERMISSIONREQUEST_DENY: `${prefix} serviceprincipal permissionrequest deny`,
  SERVICEPRINCIPAL_PERMISSIONREQUEST_LIST: `${prefix} serviceprincipal permissionrequest list`,
  SP_PERMISSIONREQUEST_APPROVE: `${prefix} sp permissionrequest approve`,
  SP_PERMISSIONREQUEST_DENY: `${prefix} sp permissionrequest deny`,
  SP_PERMISSIONREQUEST_LIST: `${prefix} sp permissionrequest list`,
  SITE_ADD: `${prefix} site add`,
  SITE_GET: `${prefix} site get`,
  SITE_LIST: `${prefix} site list`,
  SITE_APPCATALOG_ADD: `${prefix} site appcatalog add`,
  SITE_APPCATALOG_REMOVE: `${prefix} site appcatalog remove`
};